name: Build and Deploy GitHub Pages

on:
  push:
    paths:
      - '_config.yml'
      - 'index.md'
      - '_guides/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
