on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-tables:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install -y jq && chmod +x programs/update-tables.bash && programs/update-tables.bash data.json tables.md
      - uses: EndBug/add-and-commit@v9
        with:
          message: "Updated tables.md"
          add: "tables.md"
          push: true
