on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-tables:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install -y jq && chmod +x programs/update-tables.bash && programs/update-tables.bash data.json
      - uses: actions/upload-artifact@v3
        with:
          path: tables.md
